Repository magento/async-import, pull requests merged in 2019-05, with the labels that each got.

#88 delete source by uuid
  app/code/Magento/ImportService/Api/SourceRepositoryInterface.php
  app/code/Magento/ImportService/Model/Source/Command/DeleteByUuid.php
  app/code/Magento/ImportService/Model/Source/Command/DeleteByUuidInterface.php
  app/code/Magento/ImportService/Model/SourceRepository.php
  app/code/Magento/ImportService/etc/di.xml
  app/code/Magento/ImportService/etc/webapi.xml
Labels: Award: category of expertise, Award: special achievement, Event: dmcdindia1, Partner: Krish TechnoLabs, partners-contribution

#90 All sources endpoint
  app/code/Magento/ImportService/Api/SourceRepositoryInterface.php
  app/code/Magento/ImportService/Model/ResourceModel/Source/Collection.php
  app/code/Magento/ImportService/Model/Source.php
  app/code/Magento/ImportService/Model/Source/Command/GetList.php
  app/code/Magento/ImportService/Model/Source/Command/GetListInterface.php
  app/code/Magento/ImportService/Model/SourceRepository.php
  app/code/Magento/ImportService/etc/di.xml
  app/code/Magento/ImportService/etc/webapi.xml
Labels: Award: category of expertise, Event: dmcdindia1, Partner: Krish TechnoLabs, partners-contribution

#92 Implement Get operation by using Technical Guidelines
  app/code/Magento/ImportService/Api/SourceRepositoryInterface.php
  app/code/Magento/ImportService/Model/Source/Command/Get.php
  app/code/Magento/ImportService/Model/Source/Command/GetInterface.php
  app/code/Magento/ImportService/Model/SourceRepository.php
  app/code/Magento/ImportService/etc/di.xml
Labels: Event: dmcdindia1, Partner: Krish TechnoLabs, partners-contribution

#93 Implement Save operation by using Technical Guidelines
  app/code/Magento/ImportService/Api/SourceRepositoryInterface.php
  app/code/Magento/ImportService/Model/Source/Command/Save.php
  app/code/Magento/ImportService/Model/Source/Command/SaveInterface.php
  app/code/Magento/ImportService/Model/SourceRepository.php
  app/code/Magento/ImportService/etc/di.xml
Labels: Award: category of expertise, Event: dmcdindia1, Partner: Krish TechnoLabs, partners-contribution

#101 Small error handling changed
  app/code/Magento/ImportService/Model/Import/Processor/Base64EncodedDataProcessor.php
  app/code/Magento/ImportService/Model/Import/Processor/ExternalFileProcessor.php
  app/code/Magento/ImportService/Model/Import/Processor/LocalPathFileProcessor.php
  app/code/Magento/ImportService/Model/Source/Validator/ImportServiceValidator.php
  app/code/Magento/ImportService/Model/Source/Validator/ValidatorInterface.php
Labels: Partner: Comwrap, partners-contribution

#16 Async import redis framework
  lib/internal/Magento/Framework/Redis/Config.php
  lib/internal/Magento/Framework/Redis/Config/ConfigBuilder.php
  lib/internal/Magento/Framework/Redis/ConfigInterface.php
  lib/internal/Magento/Framework/Redis/ConfigProvider.php
  lib/internal/Magento/Framework/Redis/ConfigProviderInterface.php
  lib/internal/Magento/Framework/Redis/README.md
  lib/internal/Magento/Framework/Redis/RedisConnection.php
  lib/internal/Magento/Framework/Redis/RedisConnectionInterface.php
  lib/internal/Magento/Framework/Redis/RedisStorage.php
  lib/internal/Magento/Framework/Redis/Test/Unit/RedisStorageTest.php
  lib/internal/Magento/Framework/Redis/composer.json
Labels: Award: complex, on hold
