Repository magento/async-import, pull requests merged in 2019-03, with the labels that each got.

#65 ASYNC-IMPORT-55: Create new ACL rule for ImportService
  app/code/Magento/ImportService/etc/acl.xml
  app/code/Magento/ImportService/etc/webapi.xml
Labels: Partner: TechDivision, partners-contribution

#52 Repeatable call endpoint and dummy ServiceContract
  app/code/Magento/ImportService/Api/ImportRestartOperationInterface.php
  app/code/Magento/ImportService/Model/ImportRestartOperation.php
  app/code/Magento/ImportService/etc/di.xml
  app/code/Magento/ImportService/etc/webapi.xml
Labels: Partner: Krish TechnoLabs, partners-contribution

#62 issue #59 correct created_at in source
  app/code/Magento/ImportService/Api/Data/SourceInterface.php
  app/code/Magento/ImportService/Model/Import/Processor/PersistentSourceProcessor.php
  app/code/Magento/ImportService/Model/Source.php
Labels: Event: kharkivcd19

#72 Fix returned type
  app/code/Magento/ImportService/Api/ImportRestartOperationInterface.php
Labels: Partner: Comwrap, partners-contribution

#69 Implement different validators for different processors
  app/code/Magento/ImportService/Model/Import/Processor/Base64EncodedDataProcessor.php
  app/code/Magento/ImportService/Model/Import/Processor/ExternalFileProcessor.php
  app/code/Magento/ImportService/Model/Import/Processor/LocalPathFileProcessor.php
  app/code/Magento/ImportService/Model/Import/SourceTypePool.php
  app/code/Magento/ImportService/Model/Import/SourceTypesValidator.php
  app/code/Magento/ImportService/Model/Import/SourceTypesValidatorInterface.php
  app/code/Magento/ImportService/Model/Import/Type/FileSourceType.php
  app/code/Magento/ImportService/Model/ImportRestartOperation.php
  app/code/Magento/ImportService/Model/Source/Validator.php
  app/code/Magento/ImportService/Model/Source/Validator/Base64Validator.php
  app/code/Magento/ImportService/Model/Source/Validator/ImportServiceValidator.php
  app/code/Magento/ImportService/Model/Source/Validator/LocalPathValidator.php
  app/code/Magento/ImportService/Model/Source/Validator/MimeTypeValidator.php
  app/code/Magento/ImportService/Model/Source/Validator/RemoteUrlValidator.php
  app/code/Magento/ImportService/Model/Source/Validator/SourceRequestValidator.php
  app/code/Magento/ImportService/Model/Source/Validator/ValidatorInterface.php
  app/code/Magento/ImportService/etc/di.xml
Labels: Award: category of expertise, Partner: Krish TechnoLabs, partners-contribution

#77 Resolve mimetype validator issue
  app/code/Magento/ImportService/Model/Source/Validator/MimeTypeValidator.php
Labels: Partner: Krish TechnoLabs, partners-contribution

#76 Create new endpoint to get source record from table using id
  app/code/Magento/ImportService/etc/webapi.xml
Labels: Partner: Krish TechnoLabs, partners-contribution
