Repository magento/async-import, pull requests merged in 2019-07, with the labels that each got.

#109 Set url /V1/import/source/csv + Changed Interface to SourceCsvUploadI…
  app/code/Magento/ImportService/Api/SourceCsvUploadInterface.php
  app/code/Magento/ImportService/Model/SourceCsvUpload.php
  app/code/Magento/ImportService/etc/di.xml
  app/code/Magento/ImportService/etc/webapi.xml
Labels: Community Insider: Magecom, community-insider-contribution

#112 Refactor names of Source -> SourceCsv
  app/code/Magento/ImportService/Api/Data/SourceCsvFormatInterface.php
  app/code/Magento/ImportService/Api/Data/SourceCsvInterface.php
  app/code/Magento/ImportService/Api/Data/SourceUploadResponseInterface.php
  app/code/Magento/ImportService/Api/SourceCsvRepositoryInterface.php
  app/code/Magento/ImportService/Api/SourceCsvUploadInterface.php
  app/code/Magento/ImportService/Model/Import/Processor/Base64EncodedDataProcessor.php
  app/code/Magento/ImportService/Model/Import/Processor/ExternalFileProcessor.php
  app/code/Magento/ImportService/Model/Import/Processor/LocalPathFileProcessor.php
  app/code/Magento/ImportService/Model/Import/Processor/PersistentSourceProcessor.php
  app/code/Magento/ImportService/Model/Import/Processor/SourceProcessorInterface.php
  app/code/Magento/ImportService/Model/Import/SourceProcessorPool.php
  app/code/Magento/ImportService/Model/Import/SourceTypePool.php
  app/code/Magento/ImportService/Model/Import/Type/FileSourceType.php
  app/code/Magento/ImportService/Model/Import/Type/SourceTypeInterface.php
  app/code/Magento/ImportService/Model/ResourceModel/Source.php
  app/code/Magento/ImportService/Model/ResourceModel/Source/Collection.php
  app/code/Magento/ImportService/Model/Source/Command/DeleteByUuid.php
  app/code/Magento/ImportService/Model/Source/Command/DeleteByUuidInterface.php
  app/code/Magento/ImportService/Model/Source/Command/Get.php
  app/code/Magento/ImportService/Model/Source/Command/GetInterface.php
  app/code/Magento/ImportService/Model/Source/Command/GetListInterface.php
  app/code/Magento/ImportService/Model/Source/Command/Save.php
  app/code/Magento/ImportService/Model/Source/Command/SaveInterface.php
  app/code/Magento/ImportService/Model/Source/Validator/Base64Validator.php
  app/code/Magento/ImportService/Model/Source/Validator/ImportServiceValidator.php
  app/code/Magento/ImportService/Model/Source/Validator/LocalPathValidator.php
  app/code/Magento/ImportService/Model/Source/Validator/MimeTypeValidator.php
  app/code/Magento/ImportService/Model/Source/Validator/RemoteUrlValidator.php
  app/code/Magento/ImportService/Model/Source/Validator/SourceRequestValidator.php
  app/code/Magento/ImportService/Model/Source/Validator/UuidValidator.php
  app/code/Magento/ImportService/Model/Source/Validator/ValidatorInterface.php
  app/code/Magento/ImportService/Model/SourceCsv.php
  app/code/Magento/ImportService/Model/SourceCsvFormat.php
  app/code/Magento/ImportService/Model/SourceCsvRepository.php
  app/code/Magento/ImportService/Model/SourceCsvUpload.php
  app/code/Magento/ImportService/Model/SourceUploadResponse.php
  app/code/Magento/ImportService/Model/SourceUploadResponseFactory.php
  app/code/Magento/ImportService/etc/di.xml
  app/code/Magento/ImportService/etc/webapi.xml
  dev/tests/api-functional/testsuite/Magento/ImportService/Api/ExternalFileProcessorTest.php
Labels: Partner: Comwrap, partners-contribution

#89 Source update put endpoint
  app/code/Magento/ImportService/Api/Data/SourceCsvInterface.php
  app/code/Magento/ImportService/Api/SourceCsvUpdateInterface.php
  app/code/Magento/ImportService/Model/SourceCsvUpdate.php
  app/code/Magento/ImportService/Model/SourceCsvUpload.php
  app/code/Magento/ImportService/etc/di.xml
  app/code/Magento/ImportService/etc/webapi.xml
Labels: Partner: Krish TechnoLabs, Progress: changes requested, partners-contribution

#116 Remove source from response for more resfull approach
  app/code/Magento/ImportService/Api/Data/SourceUploadResponseInterface.php
  app/code/Magento/ImportService/Api/SourceCsvUpdateInterface.php
  app/code/Magento/ImportService/Model/Import/Processor/PersistentSourceProcessor.php
  app/code/Magento/ImportService/Model/SourceCsvUpdate.php
  app/code/Magento/ImportService/Model/SourceUploadResponse.php
Labels: Award: complex, Partner: Comwrap, Progress: review, partners-contribution

#118 Code clean up
  app/code/Magento/ImportService/Api/Data/ImportConfigInterface.php
  app/code/Magento/ImportService/Api/Data/ImportStartResponseInterface.php
  app/code/Magento/ImportService/Api/Data/ImportStatusResponseInterface.php
  app/code/Magento/ImportService/Api/Data/ImportStatusResponseItemInterface.php
  app/code/Magento/ImportService/Api/Data/SourceCsvFormatInterface.php
  app/code/Magento/ImportService/Api/Data/SourceCsvInterface.php
  app/code/Magento/ImportService/Api/Data/SourceFormatMappingInterface.php
  app/code/Magento/ImportService/Api/Data/SourceFormatMappingValueInterface.php
  app/code/Magento/ImportService/Api/Data/SourceUploadResponseInterface.php
  app/code/Magento/ImportService/Api/ImportRestartOperationInterface.php
  app/code/Magento/ImportService/Api/ImportStartInterface.php
  app/code/Magento/ImportService/Api/ImportStatusInterface.php
  app/code/Magento/ImportService/Api/SourceCsvRepositoryInterface.php
  app/code/Magento/ImportService/Api/SourceCsvUpdateInterface.php
  app/code/Magento/ImportService/Api/SourceCsvUploadInterface.php
  app/code/Magento/ImportService/ImportServiceException.php
  app/code/Magento/ImportService/Model/Import/Processor/Base64EncodedDataProcessor.php
  app/code/Magento/ImportService/Model/Import/Processor/ExternalFileProcessor.php
  app/code/Magento/ImportService/Model/Import/Processor/LocalPathFileProcessor.php
  app/code/Magento/ImportService/Model/Import/Processor/PersistentSourceProcessor.php
  app/code/Magento/ImportService/Model/Import/Processor/SourceProcessorInterface.php
  app/code/Magento/ImportService/Model/Import/SourceProcessorPool.php
  app/code/Magento/ImportService/Model/Import/SourceTypePool.php
  app/code/Magento/ImportService/Model/Import/Type/FileSourceType.php
  app/code/Magento/ImportService/Model/Import/Type/SourceTypeInterface.php
  app/code/Magento/ImportService/Model/ImportConfig.php
  app/code/Magento/ImportService/Model/ImportRestartOperation.php
  app/code/Magento/ImportService/Model/ImportStart.php
  app/code/Magento/ImportService/Model/ImportStartResponse.php
  app/code/Magento/ImportService/Model/ImportStatus.php
  app/code/Magento/ImportService/Model/ImportStatusResponse.php
  app/code/Magento/ImportService/Model/ImportStatusResponseFactory.php
  app/code/Magento/ImportService/Model/ImportStatusResponseItem.php
  app/code/Magento/ImportService/Model/ResourceModel/Source.php
  app/code/Magento/ImportService/Model/ResourceModel/Source/Collection.php
  app/code/Magento/ImportService/Model/Source/Command/DeleteByUuid.php
  app/code/Magento/ImportService/Model/Source/Command/DeleteByUuidInterface.php
  app/code/Magento/ImportService/Model/Source/Command/GetInterface.php
  app/code/Magento/ImportService/Model/Source/Command/GetList.php
  app/code/Magento/ImportService/Model/Source/Command/GetListInterface.php
  app/code/Magento/ImportService/Model/Source/Command/SaveInterface.php
  app/code/Magento/ImportService/Model/Source/Validator/Base64Validator.php
  app/code/Magento/ImportService/Model/Source/Validator/ImportServiceValidator.php
  app/code/Magento/ImportService/Model/Source/Validator/LocalPathValidator.php
  app/code/Magento/ImportService/Model/Source/Validator/MimeTypeValidator.php
  app/code/Magento/ImportService/Model/Source/Validator/RemoteUrlValidator.php
  app/code/Magento/ImportService/Model/Source/Validator/SourceRequestValidator.php
  app/code/Magento/ImportService/Model/Source/Validator/UuidValidator.php
  app/code/Magento/ImportService/Model/Source/Validator/ValidatorInterface.php
  app/code/Magento/ImportService/Model/SourceCsv.php
  app/code/Magento/ImportService/Model/SourceCsvUpdate.php
  app/code/Magento/ImportService/Model/SourceCsvUpload.php
  app/code/Magento/ImportService/Model/SourceUploadResponse.php
  app/code/Magento/ImportService/Model/SourceUploadResponseFactory.php
  app/code/Magento/ImportService/composer.json
  app/code/Magento/ImportService/etc/db_schema_whitelist.json
  app/code/Magento/ImportService/etc/module.xml
  app/code/Magento/ImportService/registration.php
Labels: Partner: TechDivision, Progress: review, partners-contribution

#120 Implement interfaces for Start Import endpoint magento #111
  app/code/Magento/ImportService/Api/Data/ImportConfigMappingInterface.php
  app/code/Magento/ImportService/Api/Data/ImportConfigMappingProcessingRulesInterface.php
  app/code/Magento/ImportServiceApi/Api/Data/ImportConfigInterface.php
  app/code/Magento/ImportServiceApi/etc/webapi.xml
Labels: Progress: approved

#121 Fix wrong service contract
  app/code/Magento/ImportServiceApi/etc/webapi.xml
Labels: Partner: Comwrap, partners-contribution
